# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3)),
                ('birthday', models.DateTimeField(null=True)),
                ('school', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'user',
            },
        ),
    ]
