# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190120_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hometown',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='故乡'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name='手机号码'),
        ),
    ]
