# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190121_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head',
            field=models.ImageField(default='head/contactqq.png', upload_to='shop/%Y%m/%d', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2000-01-01', null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
