# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190123_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(default='head/contactqq.png', upload_to='head/%Y%m/%d', verbose_name='头像'),
        ),
    ]
