# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190123_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='收货人')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='市')),
                ('area', models.CharField(max_length=20, verbose_name='区')),
                ('brief', models.CharField(max_length=255, verbose_name='详情地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否设置为默认')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='创建人')),
            ],
            options={
                'verbose_name_plural': '收货地址管理',
            },
        ),
    ]
