# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20, verbose_name='分类名')),
                ('classintro', models.TextField(verbose_name='分类简介')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品分类表',
                'db_table': 'CommodityClassModel',
            },
        ),
        migrations.CreateModel(
            name='CommodityPictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='图片地址')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品相册表',
                'db_table': 'CommodityPictureModel',
            },
        ),
        migrations.CreateModel(
            name='CommoditySkuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('intro', models.TextField(verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('num', models.PositiveIntegerField(verbose_name='库存')),
                ('sellnum', models.PositiveIntegerField(verbose_name='销量')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo地址')),
                ('is_putaway', models.BooleanField(verbose_name='是否上架')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityClassModel', verbose_name='商品分类ID')),
            ],
            options={
                'verbose_name': '商品SKU表',
                'db_table': 'CommoditySkuModel',
            },
        ),
        migrations.CreateModel(
            name='CommoditySpuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('detail', models.TextField(verbose_name='详情')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品SPU表',
                'db_table': 'CommoditySpuModel',
            },
        ),
        migrations.CreateModel(
            name='CommodityUnitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitname', models.CharField(max_length=100, verbose_name='单位名称')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品单位表',
                'db_table': 'CommodityUnitModel',
            },
        ),
        migrations.AddField(
            model_name='commodityskumodel',
            name='spu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommoditySpuModel', verbose_name='商品SPU_ID'),
        ),
        migrations.AddField(
            model_name='commodityskumodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommodityUnitModel', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='commoditypicturemodel',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommoditySkuModel', verbose_name='商品SKU_ID'),
        ),
    ]
