# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditypicturemodel',
            name='picture',
            field=models.ImageField(upload_to='head/%Y%m/%d', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='commodityskumodel',
            name='logo',
            field=models.ImageField(upload_to='head/%Y%m/%d', verbose_name='logo地址'),
        ),
    ]
