# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20190123_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='活动名称')),
                ('img_url', models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='活动图片地址')),
                ('url_site', models.URLField(verbose_name='活动的url地址')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityZoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='活动专区名称')),
                ('brief', models.CharField(blank=True, max_length=200, null=True, verbose_name='活动专区的简介')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='上否上线')),
            ],
            options={
                'verbose_name': '活动专区管理',
                'verbose_name_plural': '活动专区管理',
            },
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='轮播活动名')),
                ('img_url', models.ImageField(upload_to='banner/%Y%m/%d', verbose_name='轮播图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '轮播管理',
                'verbose_name_plural': '轮播管理',
            },
        ),
        migrations.AlterModelOptions(
            name='commodityclassmodel',
            options={'verbose_name_plural': '商品分类管理'},
        ),
        migrations.AlterModelOptions(
            name='commoditypicturemodel',
            options={'verbose_name_plural': '商品相册管理'},
        ),
        migrations.AlterModelOptions(
            name='commodityskumodel',
            options={'verbose_name_plural': '商品SKU表'},
        ),
        migrations.AlterModelOptions(
            name='commodityspumodel',
            options={'verbose_name_plural': '商品SPU管理'},
        ),
        migrations.AlterModelOptions(
            name='commodityunitmodel',
            options={'verbose_name_plural': '商品单位管理'},
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='Commodity_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.CommoditySkuModel', verbose_name='商品SKU'),
        ),
        migrations.AddField(
            model_name='activityzonemodel',
            name='goods_sku',
            field=models.ManyToManyField(to='commodity.CommoditySkuModel', verbose_name='商品'),
        ),
    ]
