# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20190123_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityzonemodel',
            options={'verbose_name': '首页活动管理', 'verbose_name_plural': '首页活动管理'},
        ),
        migrations.AlterModelOptions(
            name='bannermodel',
            options={'verbose_name': '首页轮播管理', 'verbose_name_plural': '首页轮播管理'},
        ),
        migrations.AlterModelOptions(
            name='commodityskumodel',
            options={'verbose_name_plural': '商品SKU管理'},
        ),
        migrations.AddField(
            model_name='activityzonemodel',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityzonemodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='activityzonemodel',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
